version: '3.4'

services:
  banking.api:
    image: ${DOCKER_REGISTRY-}bankingapi
    container_name: api
    build:
      context: .
      dockerfile: Banking.Api/Dockerfile
    ports:
      - "8080"
      - "8081"
    depends_on:
      - banking.rediscache
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://dashboard:18889
    networks:
      - otel
  banking.dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    container_name: dashboard
    ports:
      - 18888:18888
    networks:
      - otel
  banking.rediscache:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    command: --requirepass redis
    networks:
      - otel
networks:
  otel:  
volumes:
  banking.rediscache:
    driver: local